title: Scanning and Enumeration
nav:
  - Overview: README.md
  - Network Scanning: network-scanning
  - Banner Grabbing: banner-grabbing
  - Nikto and DIRB: nikto-and-dirb
  - WPScan: wpscan
  - Droopescan and Drupwn: droopescan
  - DNS Enumeration: dns-enumeration
  - DNS Zone Transfer: dns-zone-transfer
  - Port Knocking: port-knocking
